### ISSUE TITLE
Multi GPU on AWS g2.8x large

### ISSUE THREAD

**Issue by lolz0r** [NVIDIA/caffe#15]
Hello,
I am unable to run this fork in multi GPU mode when using a AWS g2.8x large instance. 

When executing the actual training with the flag ' -gpu all' I see errors relating to CUDA peer communication. After doing some research on this issue it appears that CUDA peer communication is disabled on AWS g2.8x large. 

Is it possible/practical to disable CUDA peer communication so that we can utilize multiGPU training on AWS?

Thank you for any help!

**Comment by lukeyeager** [comment]
Which version are you using? IIRC, this problem was fixed in 0e55838f364caba166cdf4a8bf38021902a923b6, which has been picked up in `v0.12.1` and greater.

You can check which version you have by looking at `libcaffe` in `build/lib`:

```bash
$ ls ~/caffe/build/lib/
libcaffe-nv.a  libcaffe-nv.so  libcaffe-nv.so.0  libcaffe-nv.so.0.12.2
```

**Comment by lolz0r** [comment]
Thank you so much for this information! What version of cuDNN is optimal for this commit?

**Comment by lolz0r** [comment]
Actually, it looks like 6.5 R2 does the trick. I will let you know how it goes. 

Thanks again!

**Comment by lukeyeager** [comment]
> What version of cuDNN is optimal for this commit?

I created a little table that should be helpful:
https://github.com/NVIDIA/caffe/wiki/Versions

**Comment by lolz0r** [comment]
Thank you for your help! I tried running caffe off the commit you specified ( 0e55838) but I still saw the same error. 

After consulting the table you linked I decided to run using 0.13 instead. After I had this working I still get the same error. 

[Attached](http://pastebin.com/vwzs4Jch) is the complete output log of my attempted training session - note that it seems to hang forever on the last line and that all GPUs read 0% activity, though they did show some RAM allocations. 

Please let me know if anything can be done.

Thank you,
Michael

**Comment by lolz0r** [comment]
This is the GPU topo, in case it is useful:

nvidia-smi topo -m
	GPU0	GPU1	GPU2	GPU3	CPU Affinity
GPU0	 X 	PHB	PHB	PHB	0-31
GPU1	PHB	 X 	PHB	PHB	0-31
GPU2	PHB	PHB	 X 	PHB	0-31
GPU3	PHB	PHB	PHB	 X 	0-31

Legend:

  X   = Self
  SOC = Path traverses a socket-level link (e.g. QPI)
  PHB = Path traverses a PCIe host bridge
  PXB = Path traverses multiple PCIe internal switches
  PIX = Path traverses a PCIe internal switch

**Comment by lukeyeager** [comment]
Go ahead and try the latest changes to the `caffe-0.12` branch. The latest version in that branch is `v0.12.2`. There are some other bugfix commits which may address your problem. See here:

https://github.com/NVIDIA/caffe/commits/caffe-0.12

If you're still seeing the same issue, this is definitely a bug. But I've run `v0.12.2` on a g2.8xlarge instance several times without any issue.

**Comment by lolz0r** [comment]
Hello again,
I checkout'd a4a4cf95326a26be9f935953aca1668665f35d81 and recompiled / reran. Same error. 

After, for the sake of completeness,  I checkout'd caffe-0.12 and recompiled / reran. Same error.

The last varible I can think of is the BLAS package. I know that some packages are more multi-core friendly then others... maybe there is some kind of blocking / locking going on with the package I have selected?

What version of BLAS would you suggest for optimal results?

**Comment by lolz0r** [comment]
Also, if you have an AMI all setup I would definitely load it up and run it against my dataset.

**Comment by lolz0r** [comment]
Interestingly after more troubleshooting the same issue occurs even when using only 1 GPU; instead now it hangs with the line: 

I0806 21:33:35.165634 43483 net.cpp:131] Setting up data

I also noticed that it interrupts the output text from the listing of the net's layer params... perhaps a deadlock of some kind?

**Comment by lolz0r** [comment]
It appears I can train other example nets but not a net based on the bvlc_googlenet example.

**Comment by lukeyeager** [comment]
> It appears I can train other example nets (with or without multi-gpu) but not a net based on the bvlc_googlenet example.

Really? That's interesting. When I get a chance, I'll try to verify that.

@slayton58, can you think of any reason why the GoogLeNet architecture would fail on EC2 (multi-GPU with no P2P)?

**Comment by slayton58** [comment]
@lukeyeager No, I can't think of a reason why googlenet would fail but other networks wouldn't. The normal issue with googlenet is memory consumption, but that should give a very different failure.

@thatguymike Any thoughts?

**Comment by lolz0r** [comment]
To note: the nature of the failure is that the system simply hangs and does not progress; so GPU activity, minimal CPU activity. It smells like a deadlock - maybe caused by the 'inceptualism' of the googlenet?

**Comment by thatguymike** [comment]
What driver are you running?  It's possible we are still trying to enable P2P when we shouldn't, but a few others have tested the same topology patch with the BVLC multi-GPU pull request without issue.  Hrmm.

**Comment by lolz0r** [comment]
I am using 346.46:

+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   33C    P0    42W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GRID K520           Off  | 0000:00:04.0     Off |                  N/A |
| N/A   30C    P0    41W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GRID K520           Off  | 0000:00:05.0     Off |                  N/A |
| N/A   34C    P0    43W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GRID K520           Off  | 0000:00:06.0     Off |                  N/A |
| N/A   31C    P0    36W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by thatguymike** [comment]
Hrmm, this should work.  If you are comfortable with a little coding, take a look at parallel.cpp and you can see where we walk the topology.  On AWS, things should fall through multi-ASIC boards and P2P boards into default memcopy.

Also, does 1 and 2 GPU work correctly?  Also, when you do run, do you see the process listed on the devices you think you should be running on?

**Comment by lolz0r** [comment]
After doing some deep troubleshooting the issue has been discovered! 

It appears that when using the same DB file for training as well as testing causes the deadlock to occur. What is amusing about this is that on the mainline caffe branch locally (1 GPU) this configuratoin works fine. However, when using the same DB for both testing and training the system halts and no error text is apparent. 

Moral of the story: Don't be too clever & haste when prototyping ideas!

Thanks for all the help guys!
